[package]
name = "librespot-protocol"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"

[dependencies]
protobuf = "~1.0.4"

[dependencies.mod_path]
git = "https://github.com/simphax/rust-std-candidates.git"
branch = "dev"